# Generated by Django 2.0.5 on 2018-06-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='static/images/crmblog/post_photos')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
