# Generated by Django 2.0.5 on 2018-06-09 19:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(blank=True, upload_to='static/images/crmblog/post_photos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
