# Generated by Django 2.0.5 on 2018-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0003_auto_20180613_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
