# Generated by Django 2.0.5 on 2018-06-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0005_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_plain',
            field=models.TextField(blank=True),
        ),
    ]
