# Generated by Django 2.0.5 on 2018-06-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0006_post_content_plain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_plain',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
