# Generated by Django 2.0.5 on 2018-06-27 17:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0007_auto_20180626_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
