# Generated by Django 2.0.5 on 2018-12-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0009_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(upload_to='static/images/crmblog/post_photos'),
        ),
    ]
