# Generated by Django 2.0.5 on 2019-02-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LedStripModel',
            new_name='LedStrip',
        ),
    ]
